plugins {
    id 'java'
    id 'com.gradleup.shadow' version '8.3.6'
}

group = 'net.stormboundmc'
version = '0.2.0-SNAPSHOT'

repositories {
    mavenCentral()

    maven {
        name = 'papermc'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }

    maven {
        name = 'Querz'
        url = 'https://jitpack.io'
    }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.1-R0.1-SNAPSHOT'

    implementation 'org.xerial:sqlite-jdbc:3.50.3.0'

    implementation 'com.github.Querz:NBT:6.1'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

processResources {
    inputs.property 'version', project.version

    filesMatching('plugin.yml') {
        expand 'version': project.version
    }
}

shadowJar {
    archiveBaseName = 'StormboundSkyblock'
    archiveClassifier = ''

    relocate 'org.sqlite', 'net.stormboundmc.libs.sqlite'
    relocate 'net.querz', 'net.stormboundmc.libs.nbt'
}

build {
    dependsOn shadowJar
}