name: SkyFoundry
version: "${version}"
main: net.skyfoundry.SkyFoundry
api-version: "1.21"

description: A lightweight custom SkyBlock core built for SkyFoundry.

commands:
  island:
    description: Main SkyFoundry island command.
    usage: /island
    aliases:
      - is

permissions:
  skyfoundry.admin.bypass:
    description: Bypass SkyFoundry island protection.
    default: op
