name: StormboundSkyblock
version: "${version}"
main: net.stormboundmc.skyblock.StormboundSkyblock
api-version: "1.21"

description: A lightweight custom SkyBlock core built for Stormbound's SkyFoundry server.

commands:
  island:
    description: Main SkyFoundry island command.
    usage: /island
    aliases:
      - is

permissions:
  stormbound.skyblock.admin:
    description: Bypass SkyFoundry island protection.
    default: op
